//  Copyright (c) 2025-2026 Peter Buenafuente Summerland.
//  All rights reserved.
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0.


// This is only used by functions generated by the CmdArgLibMacros module. We keep
// it here, in CmdArgLibCore, so that the functions can run even if the macros are not
// used. I.e., their generared output is copied and pasted in the code.

// A  struct with generic methods that return parsed values
public struct __ValueInitializer {

    let parsedValues: [ParameterName: ParsedValue]
    var messages: [String]

    /// Initialize and instance
    public init(parsedValues: [ParameterName: ParsedValue]) {
        self.parsedValues = parsedValues
        self.messages = []
    }

    /// Parse a flag
    public func __parseFlag(for name: ParameterName, _ messages: inout [String]) -> Flag {
        return Flag(parsedValues[name]?.encountered ?? false)
    }

    public func __parseRestValues(for name: ParameterName, _ defaultValue: Rest?, _ messages: inout [String]) -> Rest?
    {
        let defaultElements = defaultValue?.elements
        guard let values = __parseArrayValues(for: name, defaultElements, &messages) else { return nil }
        return Rest(values)
    }

}

extension __ValueInitializer {

    /// Parse a simple CmdArgBasicType
    public func __parseValue<T: CmdArgBasicType>(for name: ParameterName, _ defaultValue: T?, _ messages: inout [String] ) -> T?
    {
        guard let parsedValue = parsedValues[name] else {
            return defaultValue
        }
        guard parsedValue.isValid else {
            messages.append("Invalid parsed value for parameter: \(name)")
            return nil
        }
        guard let rawString = parsedValue.values.last else {
            return nil
        }
        if let value = T.initFromString(rawString) {
            return value
        }
        let typeElementName = ParameterFormatter.elementTypeName(of: parsedValue.parameter)
        let valueString = parsedValue.values.last ?? "Value error"
        let label = parsedValue.parsedLabels.last
        messages.append(invalidValueStringMsg(typeElementName, valueString, after: label))
        return nil
    }

    /// Parse optional  CmdArgBasicType
    public func __parseOptionalValue<T: CmdArgBasicType>(for name: ParameterName, _ messages: inout [String]) -> T? {
        return __parseValue(for: name, nil, &messages)
    }

     /// Parse a list of CmdArgBasicType
    public func __parseArrayValues<T: CmdArgBasicType>(for name: ParameterName, _ defaultValue: [T]?, _ messages: inout [String]) -> [T]?
    {
        guard let parsedValue = parsedValues[name], parsedValue.isValid, !parsedValue.values.isEmpty
        else {
            return defaultValue
        }
        var typeElementName = ParameterFormatter.elementTypeName(of: parsedValue.parameter)
        if typeElementName.hasSuffix("...") {
            typeElementName = String(typeElementName.dropLast(3))
        }
        let elementStrings = parsedValue.values.map { $0.trimmingCharacters(in: .whitespaces) }
        var elements = [T]()
        for (i, elementString) in elementStrings.enumerated() {
            if let element = T.initFromString(elementString) {
                elements.append(element)
            } else {
                var label = parsedValue.parsedLabels.first
                if i < parsedValue.parsedLabels.count {
                    label = parsedValue.parsedLabels[i]
                }
                messages.append(invalidValueStringMsg(typeElementName, elementString, after: label))
            }
        }
        return elements
    }
}

extension __ValueInitializer {

    /// Parse a simple RawArg
    public func __parseValue(for name: ParameterName, _ defaultValue: RawArg?, _ messages: inout [String] ) -> RawArg?
    {
        guard let parsedValue = parsedValues[name], parsedValue.isValid, !parsedValue.values.isEmpty else {
            return defaultValue
        }
        guard let value = parsedValue.values.last, let position = parsedValue.positions.last else {
            return nil
        }

        let rawArg = RawArg(parameterName: name, position: Double(position), value: value, label: parsedValue.parsedLabels.last)
        return rawArg
    }

    /// Parse an optional RawArg
    public func __parseOptionalValue(for name: ParameterName, _ messages: inout [String] ) -> RawArg?
    {
        let nilRawArg: RawArg? = nil
        return __parseValue(for: name, nilRawArg, &messages)
    }

    /// Parse a list of RawArg
    public func __parseArrayValues(for name: ParameterName, _ defaultValue: [RawArg]?, _ messages: inout [String]) -> [RawArg]?
    {
        guard let parsedValue = parsedValues[name], parsedValue.isValid, !parsedValue.values.isEmpty
        else {
            return defaultValue
        }
        let values = parsedValue.values
        let positions = parsedValue.positions
        let parsedLabels = parsedValue.parsedLabels
        if values.isEmpty { return [] }
        var rawArgs: [RawArg] = []
        let labelsMax = parsedLabels.count - 1  // zero if variant, values.count - 1 if array
        let positionsMax = positions.count - 1 //
        let multiValue = positionsMax == 0 && values.count > 1
        for i in 0..<values.count {
            var position = Double(positions[min(i, positionsMax)])
            if multiValue {
                position += Double(i) / 100
            }
            let label = labelsMax < 0 ? "nil" : parsedLabels[min(i, labelsMax)]
            let value = values[i]
            let rawArg = RawArg(parameterName: name, position: position, value: value, label: label)
            rawArgs.append(rawArg)
        }
        return rawArgs
    }
}

// This is used CmdArgLibCommandSpec module and in this module
public func invalidValueStringMsg(_ typeElementName: String, _ valueString: String, after label: String?) -> String {
    var elementName = typeElementName
    if elementName.hasSuffix("...") {
        elementName.removeLast(3)
    }
    var message = "\"\(valueString)\" is not a valid \(typeElementName)"
    if let label {
        message += " after \(label)"
    }
    return message
}
